let randomChoiceToComputer = () => parseInt(Math.random() * (4 - 1) + 1); //Generating a number between 1 and 3

function computerChoice() {
  // Taking the value generated by the machine and setting it as a computer choice.
  let choice;
  switch (randomChoiceToComputer()) {
    case 1:
      return (choice = "rock");
    case 2:
      return (choice = "paper");
    case 3:
      return (choice = "scissors");
    default:
      return console.log("error");
  }
}

function playerChoice() {
  playerChoice = parseInt(
    prompt(`CHOOSE A NUMBER:
  1 - Rock;
  2 - Paper;
  3 - Scissors;`)
  );
  return playerChoice;
}
