// This function generates a number beetwen 1 and 3
let randomChoiceToComputer = () => parseInt(Math.random() * (4 - 1) + 1);

// This function takes the value generated by the machine and sets it up as a computer choice.
function computerChoice() {
  let choice;
  switch (randomChoiceToComputer()) {
    case 1:
      return (choice = "rock");
    case 2:
      return (choice = "paper");
    case 3:
      return (choice = "scissors");
    default:
      return console.log("error");
  }
}

// This function take a input from user and determine one choice from player.
function defPlayerChoice() {
  let defPlayerChoice;
  playerChoice = parseInt(
    prompt(`CHOOSE A NUMBER:
  1 - Rock;
  2 - Paper;
  3 - Scissors;`)
  );

  switch (playerChoice) {
    case 1:
      return (defPlayerChoice = "rock");
    case 2:
      return (defPlayerChoice = "paper");
    case 3:
      return (defPlayerChoice = "scissors");
    default:
      return console.log("error");
  }
}

//This function starts the game and loops the game five times.
function game() {
  let choicePC;
  let choicePlayer;
  let scorePc = 0;
  let scorePlayer = 0;
  let score;

  for (let i = 1; i <= 5; i++) {
    choicePC = computerChoice();
    choicePlayer = defPlayerChoice();

    console.log(`\n\nRound ${i}!\n\n\n\n`);

    console.log(`PC: ${choicePC} ||| Player: ${choicePlayer}`);
    // Determine the chapion

    // Draw
    if (choicePC === choicePlayer) {
      console.log("Draww!!");
    }
    // Player win
    else if (
      (choicePlayer === "rock" && choicePC === "scissors") ||
      (choicePlayer === "scissors" && choicePC === "paper") ||
      (choicePlayer === "paper" && choicePC === "rock")
    ) {
      console.log("Player WINN!");
      scorePlayer += 1;
    }
    // PC WIN
    else {
      console.log("PC WINN!");
      scorePc += 1;
    }

    score = `FINAL RESULT ->>> PC: ${scorePc} | Player: ${scorePlayer}`;
    console.log(score);
  }

  return score;
}
